name: Yuriy Shiryaev
description: Finacial graphic designer
meta_description: "Finacial graphic designer based in Prague, Czech Republic. The most inspiration I find in meaningful, logical and reasonable design."

markdown: kramdown
highlighter: rouge
logo: true 
paginate_path: "page:num"
timezone: CZ
domain_name: 'http://yuriy.eu'
baseurl:
plugins:
  - jekyll-feed
paginate: 7
collections: 
 projects:
  output: true

# Details for the RSS feed generator
url:            'http://yuriy.eu'
author:         'Yuriy Shiryaev'
twitter: 'yuriysteam'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/